services:
  snippet-db:
    image: postgres:16-alpine
    container_name: snippet-db
    env_file: [.env]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data

  language-service:
    image: ghcr.io/ingenieria-de-sistemas-123/language-service:latest
    platform: linux/amd64
    container_name: language-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  asset-service:
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    container_name: asset-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  snippet-service:
    build: .
    container_name: snippet-service
    depends_on:
      snippet-db:
        condition: service_healthy
      language-service:
        condition: service_started
      asset-service:
        condition: service_started
      redis:
        condition: service_healthy
    env_file: [.env]
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LANGUAGE_BASE_URL=http://language-service:8080
      - ASSET_SERVICE_BASE_URL=http://asset-service:8080
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - JAVA_TOOL_OPTIONS=-javaagent:/newrelic/newrelic.jar

volumes:
  pg_data:
