spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true

management.endpoints.web.exposure.include: health,info

language:
  base-url: ${LANGUAGE_BASE_URL}

snippet:
  file-types:
    - language: printscript
      extension: prs
    - language: python
      extension: py
    - language: java
      extension: java
    - language: golang
      extension: go
