spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      url: ${SPRING_DATA_REDIS_URL:redis://redis:6379}

management.endpoints.web.exposure.include: health,info

language:
  base-url: ${LANGUAGE_BASE_URL}

snippet:
  file-types:
    - language: printscript
      extension: prs
    - language: python
      extension: py
    - language: java
      extension: java
    - language: golang
      extension: go
