name: CI
on:
  push: { branches: [ main, dev ] }
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin,
          java-version: '21',
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew clean build test jacocoTestReport --no-daemon
